version: '3.8'

services:
  financetrack-web:
    container_name: financetrack-web
    build: .   # Adjust path to your financetrack app
    ports:
      - "${HOST_PORT}:3000"
    env_file:
      - ./.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - biztrackkos-2_default

networks:
  biztrackkos-2_default:
    external: true

